language: julia
os:
  - linux
  - osx
julia:
  - 0.6
  - 0.7
  - 1.0
  - nightly
matrix:
  fast_finish: true
  allow_failures:
    - julia: nightly
notifications:
  email: false
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - |
    julia --depwarn=error -e '
      VERSION >= v"0.7.0-DEV.3656" && using Pkg
      ENV["PYTHON"] = ""
      # python 3.7 does not seem to work correctly, so lets try manually setting the root python version
      # to 3.6
      Pkg.add("Conda"); using Conda; Conda.add("python=3.6")
      if VERSION >= v"0.7.0-DEV.5183" && (isfile("Project.toml") || isfile("JuliaProject.toml"))
          Pkg.build(); Pkg.build("PyCall"); Pkg.test(coverage=true)
      else
          Pkg.clone(pwd()); Pkg.build("PyCall"); Pkg.build("Keras"); Pkg.test("Keras"; coverage=true)
      end'
after_success:
  - |
    julia -e '
      VERSION >= v"0.7.0-DEV.3656" && using Pkg
      VERSION >= v"0.7.0-DEV.5183" || cd(Pkg.dir("Keras"))
      Pkg.add("Coverage"); using Coverage
      Codecov.submit(process_folder())'
